WebApplication1/Models/Menadzer/LinijaVozacDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class LinijaVozacDodajVM
    {
        public List<SelectListItem> Vozaci{ get; set; }
        public int VozacID{ get; set; }
        public int LinijaID{ get; set; }
    }
}

WebApplication1/Models/Menadzer/LinijaVozacPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class LinijaVozacPrikazVM
    {
        public class Row
        {
            public int VozacID { get; set; }
            public string ImePrezime { get; set; }
        }
        public int LinijaID { get; set; }
        public string NazivLinije { get; set; }
        public List<Row> redovi { get; set; }
    }
}

WebApplication1/Models/Menadzer/ObavijestDodajVM.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class ObavijestUrediVM
    {
        public int ObavijestID { get; set; }
        public string Naslov { get; set; }
        public string Podnaslov { get; set; }
        public string Opis { get; set; }
        public string Slika { get; set; }
        public string ObavijestKategorija { get; set; }
        public string DatumObjave { get; set; }  
        public bool IsAktivna{ get; set; }  
        public List<SelectListItem> Kategorije { get; set; }
        public int KategorijaID { get; set; }
    }
}

WebApplication1/Models/Menadzer/ObavijestKategorijaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class ObavijestKategorijaPrikazVM
    {
        public int ObavijestID { get; set; }
        public string Naziv { get; set; }
    }
}

WebApplication1/Models/Menadzer/ObavijestKategorijaUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class ObavijestKategorijaUrediVM
    {
        public int ObavijestID { get; set; }
        public string Naziv { get; set; }
    }
}

WebApplication1/Models/Menadzer/ObavijestPrikazVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class ObavijestPrikazVM
    {
        public class Row
        {
            public int ObavijestID { get; set; }
            public string Naslov { get; set; }
            public string Podnaslov { get; set; }
            public string Opis { get; set; }
            public string Slika { get; set; }
            public string ObavijestKategorija { get; set; }
            public string DatumObjave { get; set; }
        }
        public List<Row> obavijesti;
    }
}

WebApplication1/Models/Menadzer/TipKartePrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.TipKarte
{
    public class TipKartePrikazVM
    {
        public int TipKarteID { get; set; }
        public string Naziv { get; set; }
    }
}

WebApplication1/Models/Menadzer/TipKarteUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.TipKarte
{
    public class TipKarteUrediVM
    {
        public int TipKarteID { get; set; }
        public string Naziv { get; set; }
        public bool IsAktivan{ get; set; }
    }
}

WebApplication1/Models/Menadzer/VozacPrikazVM.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class VozacPrikazVM
    {
        public class Row
        {
            public int VozacID { get; set; }
            public string Ime { get; set; }
            public string Prezime { get; set; }
            public string DatumRodjenja{ get; set; }
            public string DatumZaposlenja { get; set; }
            public string BrojVozacke { get; set; }
        }
        public List<Row> Vozaci;
        public string Pretraga { get; set; }
    }
}

WebApplication1/Models/Menadzer/VozacUrediVM.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class VozacUrediVM
    {
        public class Row
        {
            public int VozacID { get; set; }
            public string Ime { get; set; }
            public string Prezime { get; set; }
            public string DatumRodjenja { get; set; }
            public string DatumZaposlenja { get; set; }
            public string BrojVozacke { get; set; }
        }
        public List<Row> Vozaci;
    }
}

WebApplication1/Models/Menadzer/VoziloPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Menadzer
{
    public class VoziloPrikazVM
    {
        public class Row
        {
            public int VoziloID { get; set; }
            public string OznakaVozila { get; set; }
            public string RegistracijskiBroj { get; set; }
            public int MaxBrojSjedista { get; set; }
            //public DateTime DatumZadnjegServisa { get; set; }
            public string DatumZadnjegServisa { get; set; }
        }

        public List<Row> Vozila;
        public string pretraga { get; set; }
    }
}

WebApplication1/Models/Menadzer/VoziloUrediVM.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.Menadzer
{
    public class VoziloUrediVM
    {
        public int VoziloID { get; set; }
        public string OznakaVozila { get; set; }
        public string RegistracijskiBroj { get; set; }
        public int MaxBrojSjedista { get; set; }
        [BindProperty, DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm}", ApplyFormatInEditMode = true)]
        //public DateTime DatumZadnjegServisa { get; set; }
        public string DatumZadnjegServisa { get; set; }
    }
}

WebApplication1/Models/Menadzer/VrstaPopustaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.VrstaPopusta
{
    public class VrstaPopustaPrikazVM
    {
        public int VrstaPopustaID { get; set; }
        public string Naziv { get; set; }
        public float Iznos { get; set; }
    }
}

WebApplication1/Models/Menadzer/VrstaPopustaUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.VrstaPopusta
{
    public class VrstaPopustaUrediVM
    {
        public int VrstaPopustaID { get; set; }
        public string Naziv { get; set; }
        public float Iznos { get; set; }
        public bool IsAktivan{ get; set; }
    }
}

WebApplication1/Controllers/MenadzerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Podaci.Klase;
using WebApplication1.Data;
using WebApplication1.Helper;
using WebApplication1.Models.Menadzer;
using WebApplication1.Models.TipKarte;
using WebApplication1.Models.VrstaPopusta;

namespace WebApplication1.Controllers
{
    //[Authorize]
    [Autorizacija(menadzer:true,kupac:false)]
    public class MenadzerController : Controller
    {
        private readonly ApplicationDbContext db;
        public MenadzerController(ApplicationDbContext DB)
        {
            db = DB;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region Vozac
        public IActionResult VozacPrikaz(string Pretraga)
        {
            var vozaci = db.Vozac.Where(x => Pretraga == null || x.Ime.Contains(Pretraga) || x.Prezime.Contains(Pretraga))
                .Select(v => new VozacPrikazVM.Row()
                {
                    VozacID = v.VozacID,
                    Ime = v.Ime,
                    Prezime = v.Prezime,
                    DatumZaposlenja = v.DatumZaposlenja,
                    DatumRodjenja = v.DatumRodjenja,
                    BrojVozacke = v.BrojVozacke
                }).ToList();
            VozacPrikazVM m = new VozacPrikazVM()
            {
                Pretraga = Pretraga
            };
            m.Vozaci = vozaci;
            return View(m);
        }
        public IActionResult VozacUredi(int VozacID)
        {
            VozacUrediVM.Row m;
            if (VozacID == 0)
            {
                m = new VozacUrediVM.Row();
                m.DatumRodjenja = DateTime.Now.Date.ToString("dd-MM-yyyy");
                m.DatumZaposlenja = DateTime.Now.Date.ToString();
            }
            else
            {
                m = db.Vozac.Where(v => v.VozacID == VozacID).Select(x => new VozacUrediVM.Row()
                {
                    VozacID = x.VozacID,
                    BrojVozacke = x.BrojVozacke,
                    DatumRodjenja = x.DatumRodjenja,
                    DatumZaposlenja = x.DatumZaposlenja,
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                }).Single();
            }
            return View(m);
        }

        public IActionResult VozacSnimi(VozacUrediVM.Row x)
        {
            Vozac v;
            if (x.VozacID == 0)
            {
                v = new Vozac();
                db.Add(v);
            }
            else
            {
                v = db.Vozac.Find(x.VozacID);
                db.Attach(v);
                db.Entry(v).State = EntityState.Modified;
            }
            v.VozacID = x.VozacID;
            v.BrojVozacke = x.BrojVozacke;
            v.DatumRodjenja = x.DatumRodjenja;
            v.DatumZaposlenja = x.DatumZaposlenja;
            v.Ime = x.Ime;
            v.Prezime = x.Prezime;
            db.SaveChanges();
            return Redirect("/Menadzer/VozacPrikaz");
        }

        public IActionResult VozacObrisi(int VozacID)
        {
            Vozac v = db.Vozac.Find(VozacID);
            List<LinijaVozac> lista = db.LinijaVozac.Where(s => s.VozacID == VozacID).ToList();
            foreach(var i in lista)
            {
                db.Remove(i);
            }
            //v.IsAktivan = false;
            db.Remove(v);
            db.SaveChanges();
            return Redirect("/Menadzer/VozacPrikaz");
        }
        #endregion
        #region Vozilo
        public IActionResult VoziloPrikaz(string pretraga)
        {
            List<VoziloPrikazVM.Row> Vozila = db.Vozilo
                .Where(v => pretraga == null || v.RegistracijskiBroj.ToLower().StartsWith(pretraga.ToLower()) || v.OznakaVozila.ToLower().StartsWith(pretraga.ToLower()))
                .Select(v => new VoziloPrikazVM.Row
                {
                    VoziloID = v.VoziloID,
                    OznakaVozila = v.OznakaVozila,
                    RegistracijskiBroj = v.RegistracijskiBroj,
                    MaxBrojSjedista = v.MaxBrojSjedista,
                    DatumZadnjegServisa = v.DatumZadnjegServisa.ToString()
                }).ToList();
            VoziloPrikazVM v = new VoziloPrikazVM();
            v.pretraga = pretraga;
            v.Vozila = Vozila;

            return View(v);
        }

        public IActionResult VoziloObrisi(int VoziloID)
        {
            Vozilo v = db.Vozilo.Find(VoziloID);
            db.Remove(v);
            db.SaveChanges();

            return Redirect("/Menadzer/VoziloPrikaz");
        }

        public IActionResult VoziloUredi(int VoziloID=0)
        {
            VoziloUrediVM v = VoziloID == 0 ? new VoziloUrediVM() { DatumZadnjegServisa = DateTime.Now.Date.ToString() } :
                db.Vozilo.Where(v => v.VoziloID == VoziloID)
                .Select(v => new VoziloUrediVM
                {
                    VoziloID = v.VoziloID,
                    OznakaVozila = v.OznakaVozila,
                    RegistracijskiBroj = v.RegistracijskiBroj,
                    MaxBrojSjedista = v.MaxBrojSjedista,
                    DatumZadnjegServisa = v.DatumZadnjegServisa
                }).Single();

            return View(v);

        }
        public IActionResult VoziloSnimi(VoziloUrediVM x)
        {
            Vozilo vozilo;
            if (x.VoziloID == 0)
            {
                vozilo = new Vozilo();
                db.Add(vozilo);

            }
            else
            {
                vozilo = db.Vozilo.Find(x.VoziloID);
            }
            vozilo.OznakaVozila = x.OznakaVozila;
            vozilo.DatumZadnjegServisa = x.DatumZadnjegServisa;
            vozilo.RegistracijskiBroj = x.RegistracijskiBroj;
            vozilo.MaxBrojSjedista = x.MaxBrojSjedista;

            db.SaveChanges();
            return Redirect("/Menadzer/VoziloPrikaz");
        }
        #endregion
        #region Obavijest
        public IActionResult ObavijestPrikaz()
        {
            List<ObavijestPrikazVM.Row> obavijesti = db.Obavijest.OrderByDescending(s=>s.ObavijestID)
                .Select(o => new ObavijestPrikazVM.Row
            {
                ObavijestID = o.ObavijestID,
                Naslov = o.Naslov,
                Podnaslov = o.Podnaslov,
                Opis = o.Opis.Substring(0,100),
                DatumObjave = o.DatumObjave,
                ObavijestKategorija = o.ObavijestKategorija.Naziv,
                Slika = KonvertovanjeSlike.GetImageBase64(o.Slika)
            }).ToList();
            ObavijestPrikazVM m = new ObavijestPrikazVM();
            m.obavijesti = obavijesti;

            return View(m);
        }

        public IActionResult ObavijestUredi(int ObavijestID)
        {
            List<SelectListItem> ok = db.ObavijestKategorija.OrderBy(n => n.Naziv)
                .Select(k => new SelectListItem
            {
                Text = k.Naziv,
                Value = k.ObavijestKategorijaID.ToString()
            }).ToList();

            ObavijestUrediVM m;
            if (ObavijestID == 0)
            {
                m = new ObavijestUrediVM
                {
                    DatumObjave = DateTime.Now.ToString(),
                    Kategorije = ok,
                };
            }
            else
            {
                m = db.Obavijest.Where(o => o.ObavijestID == ObavijestID).Select(k => new ObavijestUrediVM
                {
                    ObavijestID = k.ObavijestID,
                    Naslov = k.Naslov,
                    Podnaslov = k.Podnaslov,
                    Opis = k.Opis,
                    DatumObjave = DateTime.Now.ToString(),
                    KategorijaID = k.ObavijestKategorijaID,
                    Kategorije = ok,
                    Slika = KonvertovanjeSlike.GetImageBase64(k.Slika),
                }).Single();
            }
            return View(m);
        }
        [HttpPost]
        public IActionResult ObavijestSnimi(ObavijestUrediVM x, IFormFile file)
        {
            Obavijest o;
            if (x.ObavijestID == 0)
            {
                o = new Obavijest();
                db.Add(o);
            }
            else
            {
                o = db.Obavijest.Find(x.ObavijestID);
                db.Attach(o);
                db.Entry(o).State = EntityState.Modified;
            }
            o.Naslov = x.Naslov;
            o.Podnaslov = x.Podnaslov;
            o.Opis = x.Opis;
            o.DatumObjave = x.DatumObjave;
            o.ObavijestKategorijaID = x.KategorijaID;

            var newSlika = KonvertovanjeSlike.GetImageByteArray(file);
            if (newSlika != null)
            {
                o.Slika = newSlika;
            }

            db.SaveChanges();
            return Redirect("/Menadzer/ObavijestPrikaz");
        }
        public IActionResult ObavijestObrisi(int ObavijestID)
        {
            Obavijest o = db.Obavijest.Find(ObavijestID);
            db.Remove(o);
            db.SaveChanges();            
            return Redirect("/Menadzer/ObavijestPrikaz");
        }
        #endregion
        #region ObavijestKategorija
        public IActionResult ObavijestKategorijaPrikaz()
        {
            var m = db.ObavijestKategorija.
                Select(ob => new ObavijestKategorijaPrikazVM
                {
                    ObavijestID = ob.ObavijestKategorijaID,
                    Naziv = ob.Naziv
                })
                .ToList();
            return View(m);
        }
        public IActionResult ObavijestKategorijaUredi(int ObavijestID)
        {
            ObavijestKategorijaUrediVM m;
            if (ObavijestID == 0)
            {

WebApplication1/Views/Menadzer/LinijaVozacDodaj.cshtml
@{
    ViewData["Title"] = "LinijaVozacDodaj";
    Layout = null;
}
@model WebApplication1.Models.Menadzer.LinijaVozacDodajVM

<form asp-action="LinijaVozacSnimi" asp-controller="Menadzer">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Uredi</h3>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="LinijaID" />
                </div>
                <div>
                    <label>Vozac</label>
                    <select asp-for="VozacID" asp-items="@Model.Vozaci"></select>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)" class="btn btn-outline-warning">
                <input type="submit" name="Snimi" value="Sačuvaj" class="btn btn-outline-primary"/>
            </div>
        </div>
    </div>
</form>

WebApplication1/Views/Menadzer/ObavijestKategorijaUredi.cshtml
@{
    ViewData["Title"] = "Uredi";
    Layout = null;
}
@model WebApplication1.Models.Menadzer.ObavijestKategorijaUrediVM

<form asp-action="ObavijestKategorijaSnimi" asp-controller="Menadzer" onsubmit="return validateForm()"
      name="myForm" method="post">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
               <h3>Uredi</h3> 
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="ObavijestID" />
                </div>
                <div>
                    <label>Naziv</label>
                    <input asp-for="Naziv" name="Naziv"/>
                </div>
            </div>
            <div class="alert alert-warning alert-dismissible fade show" role="alert" style="display:none" id="poruka">
                Niste unijeli sve potrebne vrijednosti!
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)" class="btn btn-warning">
                <input type="submit" name="Snimi" value="Sačuvaj" class="btn btn-primary"/>
            </div>
        </div>
        </div>
</form>

<script>
    function validateForm() {
        var n = document.forms["myForm"]["Naziv"].value;
       
        if (n == null || n == 0) {
            document.getElementById("poruka").style.display = "block";
            return false;
        }
    }
</script>

WebApplication1/Views/Menadzer/ObavijestUredi.cshtml
@{
    ViewData["Title"] = "Uredi";
}

<h1 class="col text-center">Uredi/Dodaj obavijest</h1>
@model WebApplication1.Models.Menadzer.ObavijestUrediVM

<form method="post" enctype="multipart/form-data" asp-action="ObavijestSnimi" asp-controller="Menadzer" onsubmit="return validateForm()" name="myForm">
    <input hidden readonly asp-for="ObavijestID" /><br />
    <div class="container">
        <div class="row form-group">
            <div class="col">
                <label class="font-weight-bold">Kategorija obavijesti: </label>
            </div>
            <div class="col-10">
                <select asp-for="KategorijaID" asp-items="@Model.Kategorije" ></select><br />
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                <label asp-for="Naslov" class="control-label font-weight-bold"></label>
            </div>
            <div class="col-10">
                <input class="form-control" asp-for="Naslov" style="width:100%" name="Naslov" /><br />
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                <label asp-for="Podnaslov" class="control-label font-weight-bold"></label>
            </div>
            <div class="col-10">
                <input asp-for="Podnaslov" style="width:100%" name="Podnaslov" /><br />
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                <label asp-for="Opis" class="control-label font-weight-bold"></label>
            </div>
            <div class="col-10">
                <textarea asp-for="Opis" style="width:100%; height:200px" name="Opis">
                </textarea>
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                <label class="font-weight-bold">Odaberi sliku</label>
            </div>
            <div class="col-10">
                @if (!string.IsNullOrEmpty(Model.Slika))
                {
                    <img src="@Model.Slika" style="max-width:100px; max-height:100px" />
                }
                <input type="file" name="file" id="file" />
            </div>
        </div>
    </div>

    <br />
    <div class="form-group col text-right">
        <label class="font-italic" style="margin-right:10px;">Datum objave:</label>
        <input readonly asp-for="DatumObjave" style="border:0" /><br />
    </div>
    <div class="alert alert-warning alert-dismissible fade show" role="alert" style="display:none" id="poruka">
        Niste unijeli sve potrebne vrijednosti!
    </div>
    <div class="row">
        <div style="display:inline" class="text-left col">
            <a class="btn btn-warning" href="/Menadzer/ObavijestPrikaz">Odustani</a>
        </div>
        <div style="display:inline" class="text-right col">
            <input class="btn btn-primary" type="submit" value="Snimi" />
        </div>
    </div>
</form>
<div class="modal fade" id="ajaxPrikaz" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

</div>
<script>
    function PrikazUredi() {

        $.get("/Menadzer/ObavijestKategorijaUredi", function (data) {
                $("#ajaxPrikaz").html(data);
            })
    }
    function validateForm() {
        var naslov = document.forms["myForm"]["Naslov"].value;
        var podnaslov = document.forms["myForm"]["Podnaslov"].value;
        var opis = document.forms["myForm"]["Opis"].value;

        if ((naslov == null || naslov == 0) || (podnaslov == null || podnaslov == 0) ||
            (opis == null || opis == 0) ) {
            document.getElementById("poruka").style.display = "block";
            return false;
        }
    }
</script>

WebApplication1/Views/Menadzer/TipKarteUredi.cshtml
@{
    ViewData["Title"] = "Uredi";
    Layout = null;
}
@model WebApplication1.Models.TipKarte.TipKarteUrediVM

<form asp-action="TipKarteSnimi" asp-controller="Menadzer"  onsubmit="return validateForm()" name="myForm" method="post">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Uredi</h3>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="TipKarteID" />
                    <input hidden readonly asp-for="IsAktivan" />
                </div>
                <div>
                    <label>Naziv</label>
                    <input asp-for="Naziv" name="Naziv" />
                </div>
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="display:none" id="poruka">
                    Niste unijeli sve potrebne vrijednosti!
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)" class="btn btn-warning">
                <input type="submit" name="Snimi" value="Sačuvaj" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
<script>
    function validateForm() {
        var n = document.forms["myForm"]["Naziv"].value;

        if ((n == null || n == 0)) {
            document.getElementById("poruka").style.display = "block";
            return false;
        }
    }
</script>

WebApplication1/Views/Menadzer/VozacUredi.cshtml
@using WebApplication1.Models.Menadzer
@model VozacUrediVM.Row
@{ 
    Layout = null;
}

<form asp-action="VozacSnimi" asp-controller="Menadzer" onsubmit="return validateForm()" name="myForm" method="post">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Uredi</h3>
            </div>
            <div class="modal-body">
                <input hidden readonly asp-for="VozacID" />
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <label>Ime</label>
                        </div>
                        <div class="col">
                            <input asp-for="Ime" name="Ime" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label>Prezime</label>
                        </div>
                        <div class="col">
                            <input asp-for="Prezime" name="Prezime" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label>Broj Vozacke</label>
                        </div>
                        <div class="col">
                            <input asp-for="BrojVozacke" name="BrojVozacke" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label>Datum rođenja:</label>
                        </div>
                        <div class="col">
                            <input type="date" asp-for="@Model.DatumRodjenja" name="DatumRodjenja" />
                        </div>                        
                    </div>
                    <div class="row">
                        <div class="col">
                            <label>Datum zaposlenja</label>
                        </div>
                        <div class="col">
                            <input type="date" asp-for="@Model.DatumZaposlenja" name="DatumZaposlenja" />
                        </div>
                    </div>
                </div>
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="display:none" id="poruka">
                    Niste unijeli sve potrebne vrijednosti!
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)" class="btn btn-warning">
                <input type="submit" name="Snimi" value="Sačuvaj" class="btn btn-primary"/>
            </div>
        </div>
    </div>
</form>
<script>
    function validateForm() {
        var ime = document.forms["myForm"]["Ime"].value;
        var prezime = document.forms["myForm"]["Prezime"].value;
        var brVozacke = document.forms["myForm"]["BrojVozacke"].value;
        var datR = document.forms["myForm"]["DatumRodjenja"].value;
        var datZ = document.forms["myForm"]["DatumZaposlenja"].value;

        if ((ime == null || ime == 0) || (prezime == null || prezime == 0) || (brVozacke == null || brVozacke == 0) ||
            (datR == null || datR == 0) || (datZ == null || datZ == 0)) {
            document.getElementById("poruka").style.display = "block";
            return false;
        }
    }
</script>