WebApplication1/Models/Linija/DrzavaDodajVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class DrzavaDodajVM
    {
        public int DrzavaID { get; set; }
        public string Naziv { get; set; }
    }
}

WebApplication1/Models/Linija/DrzavaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class DrzavaPrikazVM
    {
        public class Row
        {
            public int DrzavaID { get; set; }
            public string Naziv { get; set; }
        }
        public List<Row> Drzave;
        public string pretraga;
    }
}

WebApplication1/Models/Linija/GradDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class GradDodajVM
    {
        public int GradID { get; set; }
        public string Naziv { get; set; }
        public int DrzavaID { get; set; }
        //public Drzava Drzava { get; set; }
        public List<SelectListItem> drzave;
    }
}

WebApplication1/Models/Linija/GradPrikazVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class GradPrikazVM
    {
        public class Row
        {
            public int GradID { get; set; }
            public string Naziv { get; set; }
            public int DrzavaID { get; set; }
            public string Drzava { get; set; }

        }
        public List<Row> Gradovi;
        //public List<SelectListItem> Drzave;
        public string pretraga;
    }
}

WebApplication1/Models/Linija/LinijaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class LinijaPrikazVM
    {
        public class Row
        {
            public int LinijaID { get; set; }
            public string OznakaLinije { get; set; }

            public int GradPolaskaGradID { get; set; }
            public string GradPolaska { get; set; }

            public int GradDolaskaGradID { get; set; }
            public string GradDolaska { get; set; }


            public bool Ponedjeljak { get; set; }
            public bool Utorak { get; set; }
            public bool Srijeda { get; set; }
            public bool Cetvrtak { get; set; }
            public bool Petak { get; set; }
            public bool Subota { get; set; }
            public bool Nedjelja { get; set; }

            public string VrijemePolaska { get; set; }
            public string VrijemeDolaska { get; set; }
        }

        public List<Row> Linije;
        public string pretraga;
    }
}

WebApplication1/Models/Linija/LinijaUrediVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class LinijaUrediVM
    {
        public int LinijaID { get; set; }
        public string OznakaLinije { get; set; }

        public int GradPolaskaGradID { get; set; }
        public string GradPolaska { get; set; }

        public int GradDolaskaGradID { get; set; }
        public string GradDolaska { get; set; }


        public bool Ponedjeljak { get; set; }
        public bool Utorak { get; set; }
        public bool Srijeda { get; set; }
        public bool Cetvrtak { get; set; }
        public bool Petak { get; set; }
        public bool Subota { get; set; }
        public bool Nedjelja { get; set; }

        public string VrijemePolaska { get; set; }
        public string VrijemeDolaska { get; set; }


        public string[] DaniUSedmici { get; set; }
        public List<SelectListItem> Gradovi;
    }
}

WebApplication1/Models/Linija/StajalistePrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class StajalistePrikazVM
    {
        public class Row
        {
            public int StajaistaID { get; set; }

            public int LinijaID { get; set; }
            public string Linija { get; set; }

            public int GradID { get; set; }
            public string Grad { get; set; }

            public string SatnicaStizanja { get; set; } //u koliko sati stize bus na ovu stanicu od grada polaska
            public int RedniBrojStajalista { get; set; }
        }

        public List<Row> Stajalista;
        public string OznakaLinije;
        public int _linijaID;
    }
}

WebApplication1/Models/Linija/StajalisteUrediVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Linija
{
    public class StajalisteUrediVM
    {
        public int StajaistaID { get; set; }

        public int LinijaID { get; set; }
        public string Linija { get; set; }

        public int GradID { get; set; }
        public string Grad { get; set; }

        public string SatnicaStizanja { get; set; } //u koliko sati stize bus na ovu stanicu od grada polaska
        public int RedniBrojStajalista { get; set; }

        public List<SelectListItem> Gradovi;
        public int _linijaID { get; set; }
        public int _stajalisteID { get; set; }

    }
}

WebApplication1/Controllers/LinijaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Podaci;
using Podaci.Klase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Data;
using WebApplication1.Helper;
using WebApplication1.Models;
using WebApplication1.Models.Linija;

namespace WebApplication1.Controllers
{
    //[Authorize]
    [Autorizacija(menadzer:true,kupac:false)]
    public class LinijaController : Controller
    {
        private readonly ApplicationDbContext db;
        public LinijaController(ApplicationDbContext Db)
        {
            db = Db;
        }
        //public IActionResult Prikaz(string pretraga)
        //{
        //    List<LinijaPrikazVM.Row> Linije = db.Linija
        //        .Where(l => pretraga == null || l.OznakaLinije.ToLower().StartsWith(pretraga.ToLower()) 
        //                                     || l.GradPolaska.Naziv.ToLower().StartsWith(pretraga.ToLower()) 
        //                                     || l.GradDolaska.Naziv.ToLower().StartsWith(pretraga.ToLower()))
        //        .Select(l => new LinijaPrikazVM.Row
        //        {
        //            LinijaID = l.LinijaID,
        //            OznakaLinije = l.OznakaLinije,
        //            GradDolaskaGradID = l.GradDolaskaGradID,
        //            GradDolaska = l.GradDolaska.Naziv,
        //            GradPolaskaGradID = l.GradPolaskaGradID,
        //            GradPolaska = l.GradPolaska.Naziv,

        //            Ponedjeljak=l.Ponedjeljak,
        //            Utorak=l.Utorak,
        //            Srijeda=l.Srijeda,
        //            Cetvrtak=l.Cetvrtak,
        //            Petak=l.Petak,
        //            Subota=l.Subota,
        //            Nedjelja=l.Nedjelja,
        //            VrijemePolaska=l.VrijemePolaska,                    
        //            VrijemeDolaska=l.VrijemeDolaska,
        //        }).ToList();

        //    LinijaPrikazVM l = new LinijaPrikazVM();
        //    l.Linije = Linije;
        //    l.pretraga = pretraga;


        //    return View(l);
        //}


        //public IActionResult Obrisi(int LinijaID)
        //{
        //    List<Stajalista> stajalistazaBrisati = db.Stajalista.Where(x => x.LinijaID == LinijaID).ToList();
        //    db.RemoveRange(stajalistazaBrisati);
        //    db.SaveChanges();

        //    Linija linija = db.Linija.Find(LinijaID);
        //    db.Remove(linija);
        //    db.SaveChanges();

        //    return Redirect("/Linija/Prikaz");
        //}

        //public IActionResult Uredi(int LinijaID)
        //{
        //    List<SelectListItem> gradovi = db.Grad.OrderBy(g => g.Naziv)
        //        .Select(g => new SelectListItem
        //        {
        //            Text = g.Naziv,
        //            Value = g.GradID.ToString()
        //        }).ToList();

        //    LinijaUrediVM linija = LinijaID == 0 ? new LinijaUrediVM() :
        //        db.Linija.Where( l=> l.LinijaID == LinijaID)
        //        .Select(l => new LinijaUrediVM
        //        {
        //            LinijaID = l.LinijaID,
        //            OznakaLinije = l.OznakaLinije,
        //            GradPolaskaGradID = l.GradPolaskaGradID,
        //            GradPolaska=l.GradPolaska.Naziv,
        //            GradDolaskaGradID = l.GradDolaskaGradID,
        //            GradDolaska=l.GradDolaska.Naziv,
        //            Ponedjeljak = l.Ponedjeljak,
        //            Utorak = l.Utorak,
        //            Srijeda = l.Srijeda,
        //            Cetvrtak = l.Cetvrtak,
        //            Petak = l.Petak,
        //            Subota = l.Subota,
        //            Nedjelja = l.Nedjelja,

        //            VrijemePolaska = l.VrijemePolaska,
        //            VrijemeDolaska = l.VrijemeDolaska,
        //        }).Single();

        //    linija.Gradovi = gradovi;

        //    return View("Uredi", linija);
        //}

        //public IActionResult Snimi(LinijaUrediVM x)
        //{
        //    Linija linija;
        //    if (x.LinijaID == 0)
        //    {
        //        linija = new Linija();
        //        db.Add(linija);
        //    }
        //    else
        //    {
        //        linija = db.Linija.Find(x.LinijaID);
        //    }
        //    linija.OznakaLinije = x.OznakaLinije;
        //    linija.GradPolaskaGradID = x.GradPolaskaGradID;
        //    linija.GradDolaskaGradID = x.GradDolaskaGradID;
        //    linija.Ponedjeljak = x.Ponedjeljak;
        //    linija.Utorak = x.Utorak;
        //    linija.Srijeda = x.Srijeda;
        //    linija.Cetvrtak = x.Cetvrtak;
        //    linija.Petak = x.Petak;
        //    linija.Subota = x.Subota;
        //    linija.Nedjelja = x.Nedjelja;
        //    linija.VrijemePolaska = x.VrijemePolaska;
        //    linija.VrijemeDolaska = x.VrijemeDolaska;

        //    linija.DaniUSedmici = new string[7];
        //    if (x.Ponedjeljak)
        //        linija.DaniUSedmici[0]=("Monday");
        //    if (x.Utorak)
        //        linija.DaniUSedmici[1]=("Tuesday");
        //    if (x.Srijeda)
        //        linija.DaniUSedmici[2] = ("Wednesday");
        //    if (x.Cetvrtak)
        //        linija.DaniUSedmici[3] = ("Thursday");
        //    if (x.Petak)
        //        linija.DaniUSedmici[4] = ("Friday");
        //    if (x.Subota)
        //        linija.DaniUSedmici[5] = ("Saturday");
        //    if (x.Nedjelja)
        //        linija.DaniUSedmici[6] = ("Sunday");

        //    db.SaveChanges();
        //    return Redirect("/Linija/Prikaz");
        //}

      
        #region Linija
        public IActionResult LinijaPrikaz(string pretraga)
        {
            List<LinijaPrikazVM.Row> Linije = db.Linija
                .Where(l => pretraga == null || l.OznakaLinije.ToLower().StartsWith(pretraga.ToLower())
                                             || l.GradPolaska.Naziv.ToLower().StartsWith(pretraga.ToLower())
                                             || l.GradDolaska.Naziv.ToLower().StartsWith(pretraga.ToLower()))
                .Select(l => new LinijaPrikazVM.Row
                {
                    LinijaID = l.LinijaID,
                    OznakaLinije = l.OznakaLinije,
                    GradDolaskaGradID = l.GradDolaskaGradID,
                    GradDolaska = l.GradDolaska.Naziv,
                    GradPolaskaGradID = l.GradPolaskaGradID,
                    GradPolaska = l.GradPolaska.Naziv,

                    Ponedjeljak = l.Ponedjeljak,
                    Utorak = l.Utorak,
                    Srijeda = l.Srijeda,
                    Cetvrtak = l.Cetvrtak,
                    Petak = l.Petak,
                    Subota = l.Subota,
                    Nedjelja = l.Nedjelja,
                    VrijemePolaska = l.VrijemePolaska,
                    VrijemeDolaska = l.VrijemeDolaska,
                }).ToList();

            LinijaPrikazVM l = new LinijaPrikazVM();
            l.Linije = Linije;
            l.pretraga = pretraga;


            return View(l);
        }
        public IActionResult LinijaObrisi(int LinijaID)
        {
            List<Stajalista> stajalistazaBrisati = db.Stajalista.Where(x => x.LinijaID == LinijaID).ToList();
            db.RemoveRange(stajalistazaBrisati);
            db.SaveChanges();

            Linija linija = db.Linija.Find(LinijaID);
            db.Remove(linija);
            db.SaveChanges();

            return Redirect("/Linija/LinijaPrikaz");
        }
        public IActionResult LinijaUredi(int LinijaID)
        {
            List<SelectListItem> gradovi = db.Grad.OrderBy(g => g.Naziv)
                .Select(g => new SelectListItem
                {
                    Text = g.Naziv,
                    Value = g.GradID.ToString()
                }).ToList();

            LinijaUrediVM linija = LinijaID == 0 ? new LinijaUrediVM() :
                db.Linija.Where(l => l.LinijaID == LinijaID)
                .Select(l => new LinijaUrediVM
                {
                    LinijaID = l.LinijaID,
                    OznakaLinije = l.OznakaLinije,
                    GradPolaskaGradID = l.GradPolaskaGradID,
                    GradPolaska = l.GradPolaska.Naziv,
                    GradDolaskaGradID = l.GradDolaskaGradID,
                    GradDolaska = l.GradDolaska.Naziv,
                    Ponedjeljak = l.Ponedjeljak,
                    Utorak = l.Utorak,
                    Srijeda = l.Srijeda,
                    Cetvrtak = l.Cetvrtak,
                    Petak = l.Petak,
                    Subota = l.Subota,
                    Nedjelja = l.Nedjelja,

                    VrijemePolaska = l.VrijemePolaska,
                    VrijemeDolaska = l.VrijemeDolaska,
                }).Single();

            linija.Gradovi = gradovi;

            return View( linija);
        }

        public IActionResult LinijaSnimi(LinijaUrediVM x)
        {
            Linija linija;
            if (x.LinijaID == 0)
            {
                linija = new Linija();
                db.Add(linija);
            }
            else
            {
                linija = db.Linija.Find(x.LinijaID);
            }
            linija.OznakaLinije = x.OznakaLinije;
            linija.GradPolaskaGradID = x.GradPolaskaGradID;
            linija.GradDolaskaGradID = x.GradDolaskaGradID;
            linija.Ponedjeljak = x.Ponedjeljak;
            linija.Utorak = x.Utorak;
            linija.Srijeda = x.Srijeda;
            linija.Cetvrtak = x.Cetvrtak;
            linija.Petak = x.Petak;
            linija.Subota = x.Subota;
            linija.Nedjelja = x.Nedjelja;
            linija.VrijemePolaska = x.VrijemePolaska;
            linija.VrijemeDolaska = x.VrijemeDolaska;

            linija.DaniUSedmici = new string[7];
            if (x.Ponedjeljak)
                linija.DaniUSedmici[0] = ("Monday");

WebApplication1/Views/Linija/DrzavaPrikaz.cshtml
@model WebApplication1.Models.Linija.DrzavaPrikazVM 

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikazDrzava"
            onclick="DrzavaUredi(0)">
        Dodaj
    </button>
@*<button type="button" onclick="PrikazDodaj()" class="btn btn-primary" style="margin-bottom:10px">Dodaj</button>*@
<form>
    <input name="pretraga" value="@Model.pretraga"/>
    <input type="submit" value="Trazi" />
</form>
@*<div id="ajaxPrikaz" ></div>*@
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Akcija</th>
            
        </tr>
    </thead>

    <tbody>
        @foreach (var d in Model.Drzave)
        {
            <tr>
                <td>@d.Naziv</td>
                <td>
                <button type="button", class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikazDrzava"
                            onclick="DrzavaUredi(@d.DrzavaID)">Uredi</button>
                @*<a href="#" onclick="PrikazUredi(@d.DrzavaID)">Uredi</a>*@
                <a class="btn btn-warning" href="/Linija/DrzavaObrisi?DrzavaID=@d.DrzavaID">Obrisi</a></td>
            </tr>
        }
    </tbody>

</table>
<div class="modal fade" id="ajaxPrikazDrzava" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

</div>

<script>
    //function PrikazUredi(DrzavaID) {
    //    var url = "/Drzava/Uredi?DrzavaID=" + DrzavaID;
    //    $.get(url, function (data) {
    //        $("#ajaxPrikaz").html(data);
    //    })
    //    document.getElementById("ajaxPrikaz").style.margin = "10px";
        
    //}
    //function PrikazDodaj() {
    //    var url = "/Drzava/Uredi";
    //    $.get(url, function (data) {
    //        $("#ajaxPrikaz").html(data);
    //    })
    //    document.getElementById("ajaxPrikaz").style.margin = "10px";
       

    //}

    function DrzavaUredi(DrzavaID) {
        if (DrzavaID == 0) {
            $.get("/Linija/DrzavaUredi", function (data) {
                $("#ajaxPrikazDrzava").html(data);
            })
        }
        else {
            $.get("/Linija/DrzavaUredi?DrzavaID=" + DrzavaID, function (data) {
                $("#ajaxPrikazDrzava").html(data);
            });
        }
    }

</script>

WebApplication1/Views/Linija/DrzavaUredi.cshtml
@{ Layout = null;}
@*<style>
        form div,input,label{
            display:inline;
        }
    </style>*@

@model WebApplication1.Models.Linija.DrzavaDodajVM


<form asp-action="DrzavaSnimi" asp-controller="Linija">


    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1>Uredi</h1>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="DrzavaID" />
                </div>
                <div>
                    <label>Drzava</label>
                    <input asp-for="Naziv" />
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)">
                <input type="submit" name="Snimi" value="Sačuvaj" />
            </div>
        </div>
    </div>
</form>

WebApplication1/Views/Linija/GradPrikaz.cshtml
@model WebApplication1.Models.Linija.GradPrikazVM


    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikaz"
            onclick="PrikazUredi(0)">
        Dodaj
    </button>
    @*<button type="button" onclick="PrikazDodaj()" class="btn btn-primary" style="margin-bottom:10px">Dodaj</button>*@
    <form>
        <input name="pretraga" value="@Model.pretraga" />
        <input type="submit" value="Trazi" />
    </form>
    @*<div id="ajaxPrikaz"></div>*@
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Drzava</th>
                <th>Grad</th>
                <th>Akcija</th>

            </tr>
        </thead>

        <tbody>
            @foreach (var d in Model.Gradovi)
            {
            <tr>
                <td>@d.Drzava</td>
                <td>@d.Naziv</td>
                <td>
                    <button type="button" , class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikaz"
                            onclick="PrikazUredi(@d.GradID)">
                        Uredi
                    </button>
                    <a class="btn btn-warning" href="/Linija/GradObrisi?GradID=@d.GradID">Obrisi</a>
                </td>

                
            </tr>
            }
        </tbody>

    </table>
    <div class="modal fade" id="ajaxPrikaz" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        
    </div>


    <script>
        //function PrikazUredi(GradID) {

        //    var url;
        //    if (GradID == 0) {
        //        url = "/Grad/Uredi?GradID=" + GradID;
        //    }
        //    else {
        //        url = "/Grad/Uredi";
        //    }
        //    $.get(url, function (data) {
        //        $("#ajaxPrikaz").html(data);
        //    })

        //}
        function PrikazUredi(GradID) {
            if (GradID == 0) {
                $.get("/Linija/GradUredi", function (data) {
                    $("#ajaxPrikaz").html(data);

                })
            }
            else {
                $.get("/Linija/GradUredi?GradID=" + GradID, function (data) {
                    $("#ajaxPrikaz").html(data);
                });
            }
        }
        //function PrikazDodaj() {
        //    var url = "/Drzava/Uredi";
        //    $.get(url, function (data) {
        //        $("#ajaxPrikaz").html(data);
        //    })
        //    document.getElementById("ajaxPrikaz").style.margin = "10px";


        //}


    </script>

WebApplication1/Views/Linija/GradUredi.cshtml
@model WebApplication1.Models.Linija.GradDodajVM

@{ Layout = null;}



<form asp-action="GradSnimi" asp-controller="Linija">


    <div  class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1>Uredi</h1>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="GradID" />
                </div>
                <div>
                    <label>Drzava</label>
                    <select asp-for="DrzavaID" asp-items="@Model.drzave"></select>
                </div>
                <div>
                    <label>Grad</label>
                    <input asp-for="Naziv" />
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" value="Odustani" onClick="document.location.reload(true)">
                <input type="submit" name="Snimi" value="Sačuvaj" />
            </div>
        </div>
    </div>
</form>
               

WebApplication1/Views/Linija/LinijaUredi.cshtml
@model WebApplication1.Models.Linija.LinijaUrediVM

@*@{ Layout = null;}*@



<style>
    div{
        margin-bottom: 10px;
    }
    label{
        margin-right:10px;
        width: 15%;
    }
    .glavne{
        font-weight:bold;

    }
    .cb{
        margin-left:20px;
        width:15%;
    }
    input, select, a{
        width:20%;
        margin-right:16px;
    }
    .obicni{
        height:32px;

    }
</style>
<form asp-action="LinijaSnimi" asp-controller="Linija">
      <input hidden class="obicni" asp-for="DaniUSedmici" />
            <div class="modal-header">
                <h1>Uredi</h1>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="LinijaID" />
                    <label class="glavne">Oznaka linije:</label><input class="obicni" asp-for="OznakaLinije" />
                </div>
                <div>
                    <label class="glavne">Grad polaska:</label>
                    <select class="obicni" asp-for="GradPolaskaGradID" asp-items="@Model.Gradovi"></select>
                    <label class="glavne">Vrijeme polaska:</label>
                    <input class="obicni" asp-for="VrijemePolaska" />

                </div>
                <div >
                    <label class="glavne">Grad dolaska:</label>
                    <select class="obicni" asp-for="GradDolaskaGradID" asp-items="@Model.Gradovi"></select>
                    <label class="glavne">Vrijeme dolaska:</label>
                    <input class="obicni" asp-for="VrijemeDolaska" />
                </div>
                <!--<div>-->
                   @* <a class="btn btn-info" href="/Stajalista/Prikaz?LinijaID=@Model.LinijaID"/>Stajalista</a>*@
                    <!--<div id="ajaxPrikaz"></div>
                </div>-->
                <div>
                    <label class="glavne">Dani kojim linija vozi: </label><br />
                    <label class="cb">Ponedjeljak</label><input type="checkbox" asp-for="Ponedjeljak" /><br>
                    <label class="cb">Utorak</label><input type="checkbox" asp-for="Utorak" />          <br>
                    <label class="cb">Srijeda</label><input type="checkbox" asp-for="Srijeda" />        <br>
                    <label class="cb">Cetvrtak</label><input type="checkbox" asp-for="Cetvrtak" />      <br>
                    <label class="cb">Petak</label><input type="checkbox" asp-for="Petak" />            <br>
                    <label class="cb">Subota</label><input type="checkbox" asp-for="Subota" />          <br>
                    <label class="cb">Nedjelja</label><input type="checkbox" asp-for="Nedjelja" />
                </div>
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-warning" href="/Linija/LinijaPrikaz">Odustani</a>
                <input type="submit" class="btn btn-success" name="Snimi" value="Sačuvaj" />
            </div>
      
</form>

<script>
    //function PrikazStajalista(LinijaID) {
    //    if (LinijaID == 0) {
    //        $.get("/Stajaliste/Prikaz", function (data) {
    //            $("#ajaxPrikaz").html(data);
    //        })
    //    } else {
    //        $.get("/Stajaliste/Prikaz?LinijaID=" + LinijaID, function (data) {
    //            $("#ajaxPrikaz").html(data);
    //        })
    //    }
    //}
</script>

WebApplication1/Views/Linija/StajalistaUredi.cshtml
@model WebApplication1.Models.Linija.StajalisteUrediVM
@{ Layout = null;}

<form asp-action="StajalistaSnimi" asp-controller="Linija">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1>Uredi</h1>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="StajaistaID" />
                    <input hidden readonly asp-for="LinijaID" />
                    <input hidden readonly asp-for="_linijaID"/>
                </div>
                <div>
                    <label>Grad:</label>
                    <select asp-for="GradID" asp-items="@Model.Gradovi"></select>


                </div>
                <div>
                    <label>Planirani sati stizanja:</label>
                    <input asp-for="SatnicaStizanja">

                </div>

                <div>
                    <label class="cb">Redni broj stajalista</label>
                    <input asp-for="RedniBrojStajalista" />

                </div>
            </div>
            <div class="modal-footer">
                <input class="btn btn-warning" type="button" value="Odustani" onClick="document.location.reload(true)">
                <input type="submit" class="btn btn-success" name="Snimi" value="Sačuvaj" />
            </div>
        </div>
    </div>
</form>