WebApplication1/Controllers/KartaController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Podaci.Klase;
using WebApplication1.Data;
using WebApplication1.Helper;
using WebApplication1.Models.Karta;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication1.Controllers
{
    [Autorizacija(menadzer:false,kupac:true)]
    public class KartaController : Controller
    {
        private readonly ApplicationDbContext db;
        public static List<KartaPrikazVM.Row> polazni = null;
        public static List<KartaPrikazVM.Row> dolazni = null;
        private readonly UserManager<Korisnik> userManager;
        private readonly SignInManager<Korisnik> signInManager;
        public KartaController(ApplicationDbContext Db, UserManager<Korisnik> um, SignInManager<Korisnik> sm)
        {
            db = Db;
            userManager = um;
            signInManager = sm;
        }
       
        public IActionResult Prikaz(KartaPrikazVM karte)
        {
            KartaPrikazVM m;
            List<SelectListItem> polazneLinije = new List<SelectListItem>();
            List<SelectListItem> dolazneLinije = new List<SelectListItem>();

            if (polazni == null || polazni.Count()==0)
            {
                m = new KartaPrikazVM();
                m.polazni = null;
                m.dolazni = null;
            }
            else
            {
                m = new KartaPrikazVM()
                {
                    TipKarteID = karte.TipKarteID,
                    DatumPolaska = karte.DatumPolaska,
                    DatumDolaska = karte.DatumDolaska,
                    DolazisteID = karte.DolazisteID,
                    PolazisteID = karte.PolazisteID,
                    OznakaLinije=polazni.First().ImeLinije+" - "+polazni.First().VrijemePolaska,//+"\n"+dolazni.First().ImeLinije,
                    polazni = polazni,
                    dolazni=dolazni,
                };
                foreach (var p in polazni)
                {
                    if (p.SlobodnihMjesta > 0)
                    {
                        var item = new SelectListItem
                        {
                            Text = p.ImeLinije + " - " + p.VrijemePolaska,
                            Value = p.LinijaId.ToString()
                        };
                        polazneLinije.Add(item);
                    }
                }
                foreach (var p in dolazni)
                {
                    if (p.SlobodnihMjesta > 0)
                    {
                        var item = new SelectListItem
                        {
                            Text = p.ImeLinije + " - " + p.VrijemePolaska,
                            Value = p.LinijaId.ToString()
                        };
                        dolazneLinije.Add(item);
                    }
                }
            }
           
            List<SelectListItem> tip = db.TipKarte.OrderBy(n => n.Naziv).Where(s=>s.IsAktivan==true)
                .Select(t => new SelectListItem
            {
                Text = t.Naziv,
                Value = t.TipKarteID.ToString()
            }).ToList();

            List<SelectListItem> pol = db.Grad.OrderBy(n => n.Naziv).Select(t => new SelectListItem
            {
                Text = t.Naziv,
                Value = t.GradID.ToString()
            }).ToList();
            List<SelectListItem> dol = db.Grad.OrderBy(n => n.Naziv).Select(t => new SelectListItem
            {
                Text = t.Naziv,
                Value = t.GradID.ToString()
            }).ToList();

            m.LinijaDolaziste = dolazneLinije;
            m.LinijaPolaziste = polazneLinije;
            m.TipKarte = tip;
            m.Polaziste = pol;
            m.Dolaziste = dol;
            m.popusti = ListaPopustaHelper();
            m.kolicina = new int[m.popusti.Count()];
            return View(m);
        }
        public IActionResult Uredi(KartaPrikazVM x)
        {
            polazni = PronadjiLinije(x);
            int temp = x.PolazisteID;
            x.PolazisteID = x.DolazisteID;
            x.DolazisteID = temp;
            dolazni = PronadjiLinije(x);


            KartaPrikazVM xz = new KartaPrikazVM()
            {
                DolazisteID = x.PolazisteID,
                PolazisteID = x.DolazisteID,
                TipKarteID = x.TipKarteID,
                DatumPolaska = x.DatumPolaska,
                DatumDolaska = x.DatumDolaska,
                OznakaLinije=x.OznakaLinije
            };
           
            return RedirectToAction("Prikaz",xz);
           
        }
        public List<KartaPrikazVM.Row> PronadjiLinije(KartaPrikazVM x)
        {
            int polazisteRedniBroj = -1, dolazisteRedniBroj = -1;
            string vrijemePolaska = "", vrijemeDolaska = "", gradP = "", gradD = "";
            int linijaId = 0;

            List<KartaPrikazVM.Row> podlinije = new List<KartaPrikazVM.Row>();
            foreach (var t in db.Stajalista)
            {
                if (t.GradID == x.PolazisteID)
                {
                    polazisteRedniBroj = t.RedniBrojStajalista;
                    vrijemePolaska = t.SatnicaStizanja;
                    linijaId = t.LinijaID;
                    gradP = db.Grad.Find(t.GradID).Naziv;
                }
                if (t.GradID == x.DolazisteID && linijaId == t.LinijaID)
                {
                    dolazisteRedniBroj = t.RedniBrojStajalista;
                    vrijemeDolaska = t.SatnicaStizanja;
                    gradD = db.Grad.Find(t.GradID).Naziv;
                }
                if (polazisteRedniBroj < dolazisteRedniBroj && polazisteRedniBroj != -1 && dolazisteRedniBroj != -1)
                {
                    var linija = db.Linija.Where(l => l.LinijaID == linijaId).SingleOrDefault();
                    var parsedDate = DateTime.Parse(x.DatumPolaska);
                    var parsedTime = DateTime.Parse(vrijemePolaska);
                    if (linija.DaniUSedmici.Contains(parsedDate.DayOfWeek.ToString()))
                    {
                        if((parsedDate.Date==DateTime.Now.Date && parsedTime.TimeOfDay > DateTime.Now.TimeOfDay)
                         || parsedDate.Date != DateTime.Now.Date)
                        {
                            var nL = db.Linija.Where(d => d.LinijaID == linijaId).FirstOrDefault();
                            var brojZM = db.Karta.Where(w => w.NazivLinije.Contains(nL.OznakaLinije) && w.DatumPolaska==x.DatumPolaska).Count();
                            podlinije.Add(new KartaPrikazVM.Row()
                            {
                                LinijaId = linijaId,
                                RedniBrojPolazista = polazisteRedniBroj,
                                RedniBrojDolazista = dolazisteRedniBroj,
                                VrijemePolaska = vrijemePolaska,
                                VrijemeDolaska = vrijemeDolaska,
                                PolazisteNaziv = gradP,
                                DolazisteNaziv = gradD,
                                SlobodnihMjesta = 50 - brojZM
                            });
                        }
                    }
                    polazisteRedniBroj = -1;
                    dolazisteRedniBroj = -1;
                }
            }
            string stanica = "";

            List<KartaPrikazVM.Row> Pkarte = new List<KartaPrikazVM.Row>();
            foreach (var t in podlinije)
            {
                foreach (var i in db.Stajalista)
                {
                    if (t.LinijaId == i.LinijaID)
                    {
                        if (i.RedniBrojStajalista > t.RedniBrojPolazista && i.RedniBrojStajalista < t.RedniBrojDolazista)
                            stanica += db.Grad.Find(i.GradID).Naziv + " " + i.SatnicaStizanja + "\n";
                    }
                }
               

                KartaPrikazVM.Row y = new KartaPrikazVM.Row()
                {
                    LinijaId = t.LinijaId,
                    PolazisteNaziv = t.PolazisteNaziv,
                    DolazisteNaziv = t.DolazisteNaziv,
                    ImeLinije = db.Linija.Find(t.LinijaId).OznakaLinije,
                    VrijemePolaska = t.VrijemePolaska,
                    VrijemeDolaska = t.VrijemeDolaska,
                    Stajalista = stanica == "" ? "nema stajanja" : stanica,
                    SlobodnihMjesta=t.SlobodnihMjesta
                };
                Pkarte.Add(y);
                stanica = "";
            }
            return Pkarte;
        }
        [HttpPost]
        public IActionResult Kupovina(KartaPrikazVM x)
        {
            bool provjera = false;
            for (int i = 0; i < db.VrstaPopusta.Where(s=>s.IsAktivan==true).Count(); i++)
            {
                if (x.kolicina[i] > 0)
                    provjera = true;
            }
            if (!provjera || (x.TipKarteID==2 && x.LinijaDolazisteID==0))
                return Redirect(Request.Headers["Referer"].ToString());

            var cijena = db.Cijena.Where(c => (c.GradPolaskaGradID == x.PolazisteID && c.GradDolaskaGradID == x.DolazisteID)
              || (c.GradDolaskaGradID == x.PolazisteID && c.GradPolaskaGradID == x.DolazisteID)).SingleOrDefault();

            if(cijena==null)
                return Redirect(Request.Headers["Referer"].ToString());

            float iznos = 0;
            if (x.TipKarteID == 1)
                iznos = cijena.JednosmijernaKartaCijena;
            else
                iznos = cijena.PovratnaKartaCijena;

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using WebApplication1.Helper

@if (Context.GetLogiraniKorisnik() != null && Context.ProvjeriKorisnika(Context.GetLogiraniKorisnik().Id))
{
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Autobusna stanica</title>
        <link href="~/dist/css/styles.css" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>

    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-light " style="background-color:rgb(145, 194, 246)">
            <a class="navbar-brand text-dark" href="/Home/Index">Autobusna stanica</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar-->
            <ul class="navbar-nav d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:white" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i style="color:white" class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Postavke</a>
                        <div class="dropdown-divider"></div>
                        <form class="form-inline dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="nav-link btn btn-link text-dark">Odjava</button>
                        </form>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion text-light " id="sidenavAccordion" style="background-color:#616161">
                    <div class="sb-sidenav-menu">
                        <div class="nav text-light">
                            <div class="sb-sidenav-menu-heading">Upravljanje</div>
                            <a class="nav-link collapsed text-light" href="/Linija/LinijaPrikaz" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon "><i class="fas fa-calendar-alt"></i></div>
                                Linije
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link text-light" href="/Linija/LinijaPrikaz">Raspored</a>
                                    <a class="nav-link text-light" href="/Linija/GradPrikaz">Grad</a>
                                    <a class="nav-link text-light" href="/Linija/DrzavaPrikaz">Drzava</a>
                                    <a class="nav-link text-light" href="/Cijena/Prikaz">Cijene</a>
                                </nav>
                            </div>
                            <a class="nav-link text-light" href="/Menadzer/VoziloPrikaz">
                                <div class="sb-nav-link-icon"><i class="fas fa-bus"></i></div>
                                Vozilo
                            </a>
                            <a class="nav-link text-light" href="/Menadzer/VozacPrikaz">
                                <div class="sb-nav-link-icon"><i class="fa fa-users"></i></div>
                                Vozaci
                            </a>
                            <a class="nav-link collapsed text-light" href="/Menadzer/ObavijestPrikaz" data-toggle="collapse" data-target="#collapseLayouts1" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fa fa-bell"></i></div>
                                Obavijesti
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts1" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link text-light" href="/Menadzer/ObavijestPrikaz">Obavijest</a>
                                    <a class="nav-link text-light" href="/Menadzer/ObavijestKategorijaPrikaz">Obavijest Kategorije</a>
                                </nav>
                            </div>
                            <a class="nav-link text-light" href="/Menadzer/IzvjestajPrikaz">
                                <div class="sb-nav-link-icon"><i class="fas fa-file-chart-pie"></i></div>
                                Izvjestaji
                            </a>
                            <div class="sb-sidenav-menu-heading">Karte</div>
                            <a class="nav-link text-light" href="/Menadzer/TipKartePrikaz">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Tip Karte
                            </a>
                            <a class="nav-link text-light" href="/Menadzer/VrstaPopustaPrikaz">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Vrsta Popusta
                            </a>
                            @if (Context.GetLogiraniKorisnik().Id == "703e57af-e99b-4510-8af4-e3e080fa21a9")
                                {
                                    <div class="sb-sidenav-menu-heading">Dodaj menadzera</div>
                                    <a class="nav-link text-light" href="/Home/DodajMenadzera">
                                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                        Dodaj menadzera
                                    </a>
                                }
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        <span style="color:white">@User.Identity.Name @Context.GetLogiraniKorisnik().Email!</span>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <div class="container">
                    <main role="main" class="pb-3" style="padding:20px">
                        @RenderBody()
                    </main>
                </div>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            @*<div>
                                    <a href="#">Privacy Policy</a>
                                    &middot;
                                    <a href="#">Terms &amp; Conditions</a>
                                </div>*@
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>*@
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/dist/js/scripts.js"></script>
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>*@
        @*<script src="~/dist/assets/demo/chart-area-demo.js"></script>*@
        @*<script src="~/dist/assets/demo/chart-bar-demo.js"></script>*@
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="~/dist/assets/demo/datatables-demo.js"></script>
        @RenderSection("Scripts", required: false)

    </body>
</html>

}
else
{
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color:rgb(145, 194, 246)">
            <div class="container">
                <a class="navbar-brand text-light font-weight-bolder" asp-area="" asp-controller="Home" asp-action="Index">Autobusna stanica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (AutentifikacijaMVC.currentUserId != "" && Context.GetLogiraniKorisnik() != null)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bolder" asp-area="" asp-controller="Karta" asp-action="Prikaz">Kupi kartu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bolder" asp-area="" asp-controller="Karta" asp-action="KupljeneKarte">Historija</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bolder" href="https://p2057.app.fit.ba/crud/prikaz-kartica">Kreditne kartice</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bolder" asp-area="" asp-controller="" asp-action="">Feedback</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021  @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
}