WebApplication1/Models/Cijena/CijenaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Cijena
{
    public class CijenaPrikazVM
    {
        public class Row
        {
            public int CijenaID { get; set; }

            public int GradPolaskaGradID { get; set; }
            public string GradPolaska { get; set; }

            public int GradDolaskaGradID { get; set; }
            public string GradDolaska { get; set; }

            public float JednosmijernaKartaCijena { get; set; }
            public float PovratnaKartaCijena { get; set; }
        }

        public List<Row> Cijene;
        public string pretraga;
    }
}

WebApplication1/Models/Cijena/CijenaUrediVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Cijena
{
    public class CijenaUrediVM
    {
        public int CijenaID { get; set; }

        public int GradPolaskaGradID { get; set; }
        public string GradPolaska { get; set; }

        public int GradDolaskaGradID { get; set; }
        public string GradDolaska { get; set; }

        public float JednosmijernaKartaCijena { get; set; }
        public float PovratnaKartaCijena { get; set; }

        public List<SelectListItem> Gradovi; 
    }
}

WebApplication1/Controllers/CijenaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Podaci.Klase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Data;
using WebApplication1.Helper;
using WebApplication1.Models.Cijena;

namespace WebApplication1.Controllers
{
    [Autorizacija(menadzer:true,kupac:false)]
    public class CijenaController : Controller
    {
        private readonly ApplicationDbContext db;
        public CijenaController(ApplicationDbContext Db)
        {
            db = Db;
        }

        public IActionResult Prikaz(string pretraga)
        {
            List<CijenaPrikazVM.Row> cijene = db.Cijena
                .Where(c => pretraga == null || c.GradPolaska.Naziv.ToLower().StartsWith(pretraga.ToLower())
                                          || c.GradDolaska.Naziv.ToLower().StartsWith(pretraga.ToLower()))
                .Select(c => new CijenaPrikazVM.Row()
                {
                    CijenaID = c.CijenaID,
                    GradPolaskaGradID = c.GradPolaskaGradID,
                    GradPolaska = c.GradPolaska.Naziv,
                    GradDolaskaGradID=c.GradDolaskaGradID,
                    GradDolaska=c.GradDolaska.Naziv,
                    JednosmijernaKartaCijena=c.JednosmijernaKartaCijena,
                    PovratnaKartaCijena=c.PovratnaKartaCijena
                }).ToList();

            CijenaPrikazVM c = new CijenaPrikazVM();
            c.Cijene = cijene;
            c.pretraga = pretraga;

            return View(c);
        }

        public IActionResult Obrisi(int CijenaID)
        {
            Cijena cijena = db.Cijena.Find(CijenaID);
            db.Remove(cijena);
            db.SaveChanges();

            return Redirect("/Cijena/Prikaz");
        }

        public IActionResult Uredi(int CijenaID)
        {
            List<SelectListItem> gradovi = db.Grad.OrderBy(g => g.Naziv)
                .Select(g => new SelectListItem
                {
                    Text = g.Naziv,
                    Value = g.GradID.ToString()
                }).ToList();

                CijenaUrediVM cijena = CijenaID == 0 ? new CijenaUrediVM() :
                db.Cijena.Where(c => c.CijenaID == CijenaID)
                .Select(c => new CijenaUrediVM
                {
                    CijenaID = c.CijenaID,
                    GradDolaska = c.GradDolaska.Naziv,
                    GradDolaskaGradID = c.GradDolaskaGradID,
                    GradPolaska = c.GradPolaska.Naziv,
                    GradPolaskaGradID = c.GradPolaskaGradID,
                    JednosmijernaKartaCijena = c.JednosmijernaKartaCijena,
                    PovratnaKartaCijena = c.PovratnaKartaCijena
                }).Single();

            cijena.Gradovi = gradovi;

            return View("Uredi", cijena);
        }

        public IActionResult Snimi(CijenaUrediVM x)
        {
            Cijena cijena;
            if (x.CijenaID == 0)
            {
                cijena = new Cijena();
                db.Add(cijena);
            }
            else
            {
                cijena = db.Cijena.Find(x.CijenaID);
            }

            cijena.GradDolaskaGradID = x.GradDolaskaGradID;
            cijena.GradPolaskaGradID = x.GradPolaskaGradID;
            cijena.JednosmijernaKartaCijena = x.JednosmijernaKartaCijena;
            cijena.PovratnaKartaCijena = x.PovratnaKartaCijena;

            db.SaveChanges();

            return Redirect("/Cijena/Prikaz");
        }

    }
}

WebApplication1/Views/Cijena/Prikaz.cshtml
@using WebApplication1.Models.Cijena
@model CijenaPrikazVM


<button type="button" , class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikaz"
        onclick="PrikazUredi()">
    Dodaj cijenu
</button>

<form style="margin:20px 0px">
    <input class="form-control" name="pretraga" value="@Model.pretraga" style="width:50%; display:inline;" placeholder="Unesite lokaciju za pretragu"/>
    <input  class="btn btn-info" type="submit" value="Pretraga" style="display:inline;"/>
</form>

<table id="tabela" class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Lokacija 1</th>
            <th>Lokacija 2</th>
            <th>Jednosmijerna karta (BAM)</th>
            <th>Povratka karta (BAM)</th>
            <th>Akcija</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var c in Model.Cijene)
        {
        <tr>
            <td>@c.GradPolaska</td>
            <td>@c.GradDolaska</td>
            <td>@c.JednosmijernaKartaCijena</td>
            <td>@c.PovratnaKartaCijena</td>
            <td>
                <button type="button" , class="btn btn-primary" data-toggle="modal" data-target="#ajaxPrikaz"
                        onclick="PrikazUredi(@c.CijenaID)">
                    Uredi
                </button>
                <a class="btn btn-warning" href="/Cijena/Obrisi?cijenaID=@c.CijenaID">Obrisi</a>
            </td>
        </tr>
        }
    </tbody>

</table>
<div class="modal fade" id="ajaxPrikaz" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

</div>

<script>
    function PrikazUredi(CijenaID) {
        if (CijenaID == 0) {
            $.get("/Cijena/Uredi", function (data) {
                $("#ajaxPrikaz").html(data);

            })
        }
        else {
            $.get("/Cijena/Uredi?CijenaID=" + CijenaID, function (data) {
                $("#ajaxPrikaz").html(data);
            });
        }
    }
</script>

WebApplication1/Views/Cijena/Uredi.cshtml
@using WebApplication1.Models.Cijena
@model CijenaUrediVM

@{ Layout = null;}

<style>
    .form-control{
        display:inline;
        width:auto;
    }
</style>

<form asp-action="Snimi" asp-controller="Cijena">


    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1>Uredi</h1>
            </div>
            <div class="modal-body">
                <div>
                    <input hidden readonly asp-for="CijenaID" />
                </div>
                <div>
                    <label>Lokacija 1:</label>
                    <select asp-for="GradPolaskaGradID" asp-items="Model.Gradovi" class="form-control"></select>
                </div>
                <div>
                    <label>Lokacija 2:</label>
                    <select asp-for="GradDolaskaGradID" asp-items="Model.Gradovi" class="form-control"></select>
                </div>
                <div>
                    <label>Jednosmijerna karta (BAM): </label>
                    <input asp-for="JednosmijernaKartaCijena" class="form-control" />
                </div>
                <div>
                    <label>Povratna karta (BAM)</label>
                    <input asp-for="PovratnaKartaCijena" class="form-control" />
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-warning" value="Odustani" onClick="document.location.reload(true)">
                <input type="submit" class="btn btn-success" name="Snimi" value="Sačuvaj" />
            </div>
        </div>
    </div>
</form>